### ISSUE TITLE
Help with Performance on Apple M1

### ISSUE THREAD

**Issue by kellertuer** [JuliaSIMD/VectorizationBase.jl#22]
As @chriselrod asked in #21, here's the output of 

```julia
using Libdl
llvmlib = VERSION ≥ v"1.6.0-DEV.1429" ? Libdl.dlopen(Base.libllvm_path()) : Libdl.dlopen(only(filter(lib->occursin(r"LLVM\b", basename(lib)), Libdl.dllist())));
gethostcpufeatures = Libdl.dlsym(llvmlib, :LLVMGetHostCPUFeatures);
features_cstring = ccall(gethostcpufeatures, Cstring, ());
features = filter(ext -> (m = match(r"\d", ext); isnothing(m) ? true : m.offset != 2 ), split(unsafe_string(features_cstring), ','));
println(features)
```
on Julia 1.5.3 on the MacBook Pro Apple M1 (but it should be the same as on the MacBook Air since the M1 I the same as far as I know):

```Julia
SubString{String}["+sse2", "+cx16", "+sahf", "-tbm", "-avx512ifma", "-sha", "-gfni", "-fma4", "-vpclmulqdq", "-prfchw", "-bmi2", "-cldemote", "-fsgsbase", "-ptwrite", "-xsavec", "+popcnt", "-mpx", "+aes", "-avx512bitalg", "-movdiri", "-xsaves", "-avx512er", "-avx512vnni", "-avx512vpopcntdq", "-pconfig", "-clwb", "-avx512f", "-clzero", "-pku", "+mmx", "-lwp", "-rdpid", "-xop", "-rdseed", "-waitpkg", "-movdir64b", "-sse4a", "-avx512bw", "-clflushopt", "-xsave", "-avx512vbmi2", "-avx512vl", "-invpcid", "-avx512cd", "-avx", "-vaes", "+cx8", "-fma", "-rtm", "-bmi", "-enqcmd", "-rdrnd", "-mwaitx", "+sse4.1", "+sse4.2", "-avx2", "+fxsr", "-wbnoinvd", "+sse", "-lzcnt", "+pclmul", "-prefetchwt1", "-f16c", "+ssse3", "-sgx", "-shstk", "+cmov", "-avx512vbmi", "-avx512bf16", "-movbe", "-xsaveopt", "-avx512dq", "-adx", "-avx512pf", "+sse3"]
```
to be honest, I am not sure what to do with this, but I was asked to provide it. I can also do that on Julia nightly (1.6-DEV) if that helps.

**Comment by chriselrod** [comment]
I guess this is Julia running on Rosetta? Do you get
```julia
julia> Sys.ARCH
:x86_64
```
?

The M1 looks like an x86_64 CPU with only SSE. That is, like a very old CPU.

I was expecting something more like
```julia
julia> println(features)
 SubString{String}["+neon", "+fp-armv8", "+crypto", "+crc"]
```
https://github.com/chriselrod/VectorizationBase.jl/issues/21#issuecomment-740225710
Where I can see that the ARM CPU does support NEON.

**Comment by kellertuer** [comment]
Oh, sorry, yes. As I said, I am not experienced with this; It is the same config that gave the error in the other thread. Then I have to check how to get Julia native to M1.

**Comment by chriselrod** [comment]
Is there a supported* Fortran compiler for the M1 yet?
*Apparently NAG has a Fortran compiler for the M1, but I don't see [nagfor](https://www.nag.com/nagware/np/r70_doc/nagfor.html) listed [here](https://github.com/xianyi/OpenBLAS/blob/efc53b6e7e51c70d7aa718333687dc5761668738/cmake/fc.cmake).
Not sure when there'll be native support.

I guess I should start worrying about optimizing for the M1 only once it can run Julia natively?
As is, I don't know how to recognize it vs just an old x86_64.

**Comment by chriselrod** [comment]
https://github.com/JuliaLang/julia/issues/36617

**Comment by chriselrod** [comment]
But I am interested in the results of this:
```julia
using LoopVectorization, BenchmarkTools
function self_dot_1(x)
    s = zero(eltype(x))
    @avx unroll=1 for i in eachindex(x)
        s += x[i]^2
    end
    s
end
function self_dot_2(x)
    s = zero(eltype(x))
    @avx unroll=2 for i in eachindex(x)
        s += x[i]^2
    end
    s
end
function self_dot_4(x)
    s = zero(eltype(x))
    @avx unroll=4 for i in eachindex(x)
        s += x[i]^2
    end
    s
end
function self_dot_8(x)
    s = zero(eltype(x))
    @avx unroll=8 for i in eachindex(x)
        s += x[i]^2
    end
    s
end

x = rand(512);
@btime self_dot_1($x)
@btime self_dot_2($x)
@btime self_dot_4($x)
@btime self_dot_8($x)
```
For example, I get
```julia
julia> x = rand(512);

julia> @btime self_dot_1($x)
  38.775 ns (0 allocations: 0 bytes)
162.8021234109089

julia> @btime self_dot_2($x)
  23.932 ns (0 allocations: 0 bytes)
162.8021234109089

julia> @btime self_dot_4($x)
  17.550 ns (0 allocations: 0 bytes)
162.8021234109089

julia> @btime self_dot_8($x)
  17.087 ns (0 allocations: 0 bytes)
162.8021234109089
```
and, similarly for sums:
```julia
function sum_1(x)
    s = zero(eltype(x))
    @avx unroll=1 for i in eachindex(x)
        s += x[i]
    end
    s
end
function sum_2(x)
    s = zero(eltype(x))
    @avx unroll=2 for i in eachindex(x)
        s += x[i]
    end
    s
end
function sum_4(x)
    s = zero(eltype(x))
    @avx unroll=4 for i in eachindex(x)
        s += x[i]
    end
    s
end
function sum_8(x)
    s = zero(eltype(x))
    @avx unroll=8 for i in eachindex(x)
        s += x[i]
    end
    s
end
@btime sum_1($x)
@btime sum_2($x)
@btime sum_4($x)
@btime sum_8($x)
```
I get
```julia
julia> @btime sum_1($x)
  38.542 ns (0 allocations: 0 bytes)
247.23752428236378

julia> @btime sum_2($x)
  24.413 ns (0 allocations: 0 bytes)
247.23752428236375

julia> @btime sum_4($x)
  17.467 ns (0 allocations: 0 bytes)
247.23752428236372

julia> @btime sum_8($x)
  16.852 ns (0 allocations: 0 bytes)
247.23752428236372
```
I'm curious if you see much more benefit from unrolling on the M1. Because it has more execution units, it seems likely that it'd benefit from more dependency cutting.

Also, I realized there's a bug when `unroll=16`. LoopVectorization will never automatically pick a number that high, but better not to have bugs. I'll look into it.

**Comment by kellertuer** [comment]
I have never worked nor do I plan to work with Fortran, so I can not provide any help there.

For the commands you postet in the last comment – should I run that on my current Julia or wait for the native-ARM variant?

**Comment by chriselrod** [comment]
Fortran was actually checked off in Keno's issue.

I'd be interested in seeing the results currently on Rosetta, and again once there's a native version.
We should see the greater number of instructions/clock even under Rosetta.

**Comment by kellertuer** [comment]
Great, so on Rosetta, i get the following for you first block (without any recompilation or double runs)
```julia
julia> x = rand(512);

julia> @btime self_dot_1($x)
  175.996 ns (0 allocations: 0 bytes)
173.38314925173995

julia> @btime self_dot_2($x)
  85.667 ns (0 allocations: 0 bytes)
173.38314925174

julia> @btime self_dot_4($x)
  51.892 ns (0 allocations: 0 bytes)
173.38314925173995

julia> @btime self_dot_8($x)
  47.902 ns (0 allocations: 0 bytes)
173.38314925173995
```

and for the second

```julia
julia> @btime sum_1($x)
  174.907 ns (0 allocations: 0 bytes)
260.10397993782067

julia> @btime sum_2($x)
  80.664 ns (0 allocations: 0 bytes)
260.10397993782055

julia> @btime sum_4($x)
  47.943 ns (0 allocations: 0 bytes)
260.10397993782055

julia> @btime sum_8($x)
  37.596 ns (0 allocations: 0 bytes)
260.10397993782055
```

again I am not experienced with this, so If I should run anything else, or make sure I don't have this or that running aside, let me know.

**Comment by chriselrod** [comment]
I bought a Mac Mini for testing, and am running it natively now.
If anyone reads this and Hwloc_jll doesn't exist yet for Apple-AArch64, you can dev Hwloc.jl, install hwloc via some other means (I used homebrew), and then edit Hwloc.jl to remove Hwloc_jll as a dependency and define const
```julia
const libhwloc = "/opt/homebrew/lib/libhwloc.dylib"
```
where you replace the path shown above with whatever the path actually is.

To work, this will require at least VectorizationBase 0.19.23 (which at the time I write this means it needs the master branch; I would suggest using the master branch of LoopVectorization as well at least until LV 0.12.12 is released).

Some tests pass. A lot fail. I'll look into them and address them before an actual release.

I already made a few tweaks/fixes that improved performance substantially.
I haven't tried Rosetta yet, so I can't comment on how that'll compare.
My `self_dot` and `sum` times are just a little better, but they weren't really relying on LoopVectorization to optimize nor do they have too much going on otherwise.


@mcabbot tagging you in case you're interested.
